---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.api.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  database: {{ .Values.secrets.database.api.dbName | default "api" | b64enc }}
  jwtSecret: {{ .Values.secrets.api.jwtSecret | default (randAlphaNum 32) | b64enc }}
  fixedAuthTokens: {{ printf "[{\"token\":\"%s\",\"userId\":\"1\",\"authProvider\":\"openstad\"}]" (randAlphaNum 32) | b64enc }}
