---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-auth-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  database: {{ .Values.secrets.database.auth.dbName | default "auth" | b64enc }}
