---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.cms.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  apiKey: {{ .Values.secrets.cms.apiKey | default (randAlphaNum 32) | b64enc }}
  mongodbUri: {{ .Values.secrets.cms.mongodbUri | b64enc }}