---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.image.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  verificationToken: {{ .Values.admin.secrets.nextAuthSecret | default (randAlphaNum 32) | b64enc }}