apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstad-headless-ingress-update-role
rules:
  - apiGroups: ['extensions', 'networking.k8s.io']
    resources: ['ingresses']
    verbs: ['create', 'update', 'patch', 'delete', 'get', 'list', 'watch']
  - apiGroups: ['networking.k8s.io']
    resources: ['ingressclasses']
    verbs: ['get', 'list', 'watch']

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstad-headless-ingress-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstad-headless-ingress-update-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstad-headless-ingress-update-role
subjects:
  - kind: ServiceAccount
    name: openstad-headless-ingress-sa
